#! /bin/bash

regress_dir=$(dirname $0)/../regress

if [[ $1 == '-b' ]]; then
  write_bl=1
fi

echo
for file in $regress_dir/*.js; do
  bl=${file}.baseline
  base=$(basename $file)
  printf "%-40s " "${base}:"
  # Diffing baselines
  if [ -z $write_bl ]  ; then
    # Has a baseline
    if [ -f $bl ] ; then
      diff=$(diff $bl <(node $file))
      if [[ $? -eq 0 ]] ; then
        printf "[ \e[1;32m%-6s\e[0m ]\n" PASSED
      else
        printf "[ \e[1;31m%-6s\e[0m ]\n" FAILED
        echo $diff
      fi
    fi
  # Writing baselines
  else
    node $file > $bl
    if [[ $? -eq 0 ]] ; then
      printf "[ \e[1;34m%-9s\e[0m ]\n" BASELINED
    fi
  fi
done
echo
